export const SET_PIZZA_NAME = 'SET_PIZZA_NAME';
export const SET_PIZZA_DOUGH = 'SET_PIZZA_DOUGH';
export const SET_PIZZA_SIZE = 'SET_PIZZA_SIZE';
export const SET_PIZZA_SAUCE = 'SET_PIZZA_SAUCE';
export const SET_PIZZA_INGREDIENTS = 'SET_PIZZA_INGREDIENTS';
export const SET_PIZZA_COST = 'SET_PIZZA_COST';
export const ADD_PIZZA_IN_CART = 'ADD_PIZZA_IN_CART';
export const UPDATE_ADDITIONAL_COUNTER = 'UPDATE_ADDITIONAL_COUNTER';
