export const SET_PIZZA_NAME = 'SET_PIZZA_NAME';
export const SET_PIZZA_DOUGH = 'SET_PIZZA_DOUGH';
export const SET_PIZZA_SIZE = 'SET_PIZZA_SIZE';
export const SET_PIZZA_SAUCE = 'SET_PIZZA_SAUCE';
export const SET_PIZZA_INGREDIENTS = 'SET_PIZZA_INGREDIENTS';
